#pragma once

enum ErrorCode
{
    ENGINE_NOT_SUPPORT              = 0001,
    BUFFER_TYPE_NOT_SUPPORT         = 0002,
    BUFFER_SOURCE_TYPE_NOT_SUPPORT  = 0003,
    RUNTIME_UNKNOWN                 = 0004,
    RUNTIME_NOT_AVAILABLE           = 0005,
    LOAD_CONTAINER_ERROR            = 0006,
    SNPE_MODEL_BUILD_ERROR          = 0007,

    DEEPFACE_CONFIG_PATH_NOT_EXIST  = 1001,
    DEEPFACE_MODEL_PATH_NOT_EXIST   = 1002,
    DEEPFACE_HANDLE_ERROR           = 1003,

    PEDESTRIAN_CONFIG_PATH_NOT_EXIST = 1010,

};
